#pragma once
#include "..\..\source\stdafx.h"

#define dtbfix_code CTL_CODE(FILE_DEVICE_UNKNOWN, 0x12A, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)

#define rw_code CTL_CODE(FILE_DEVICE_UNKNOWN, 0x13A, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)

#define base_code CTL_CODE(FILE_DEVICE_UNKNOWN, 0x14A, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)

#define nmi_callback CTL_CODE(FILE_DEVICE_UNKNOWN, 0x15A, METHOD_BUFFERED, FILE_ANY_ACCESS)